"""chat_revolucionario_status_grupos_reacoes

Revision ID: d746a8d81c84
Revises: bf387194a72b
Create Date: 2025-11-26 20:47:37.585482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd746a8d81c84'
down_revision: Union[str, None] = 'bf387194a72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['criador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_chat_id'), 'grupos_chat', ['id'], unique=False)
    op.create_table('status_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('ultima_atividade', sa.DateTime(), nullable=False),
    sa.Column('digitando_para', sa.Integer(), nullable=True),
    sa.Column('digitando_desde', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['digitando_para'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_status_usuarios_id'), 'status_usuarios', ['id'], unique=False)
    op.create_table('membros_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('silenciado', sa.Boolean(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=False),
    sa.Column('adicionado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adicionado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membros_grupo_id'), 'membros_grupo', ['id'], unique=False)
    op.create_table('mensagens_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('editada', sa.Boolean(), nullable=False),
    sa.Column('data_edicao', sa.DateTime(), nullable=True),
    sa.Column('deletada', sa.Boolean(), nullable=False),
    sa.Column('resposta_para_id', sa.Integer(), nullable=True),
    sa.Column('anexo_url', sa.String(length=500), nullable=True),
    sa.Column('anexo_nome', sa.String(length=255), nullable=True),
    sa.Column('anexo_tamanho', sa.Integer(), nullable=True),
    sa.Column('reacoes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['resposta_para_id'], ['mensagens_grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_grupo_id'), 'mensagens_grupo', ['id'], unique=False)
    op.create_table('leituras_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ultima_mensagem_lida_id', sa.Integer(), nullable=True),
    sa.Column('data_leitura', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['ultima_mensagem_lida_id'], ['mensagens_grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leituras_grupo_id'), 'leituras_grupo', ['id'], unique=False)
    op.add_column('mensagens', sa.Column('tipo', sa.String(length=20), nullable=False, server_default='texto'))
    op.add_column('mensagens', sa.Column('status', sa.String(length=20), nullable=False, server_default='enviada'))
    op.add_column('mensagens', sa.Column('data_entrega', sa.DateTime(), nullable=True))
    op.add_column('mensagens', sa.Column('editada', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('mensagens', sa.Column('data_edicao', sa.DateTime(), nullable=True))
    op.add_column('mensagens', sa.Column('deletada', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('mensagens', sa.Column('resposta_para_id', sa.Integer(), nullable=True))
    op.add_column('mensagens', sa.Column('anexo_url', sa.String(length=500), nullable=True))
    op.add_column('mensagens', sa.Column('anexo_nome', sa.String(length=255), nullable=True))
    op.add_column('mensagens', sa.Column('anexo_tamanho', sa.Integer(), nullable=True))
    op.add_column('mensagens', sa.Column('reacoes', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'mensagens', 'mensagens', ['resposta_para_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mensagens', type_='foreignkey')
    op.drop_column('mensagens', 'reacoes')
    op.drop_column('mensagens', 'anexo_tamanho')
    op.drop_column('mensagens', 'anexo_nome')
    op.drop_column('mensagens', 'anexo_url')
    op.drop_column('mensagens', 'resposta_para_id')
    op.drop_column('mensagens', 'deletada')
    op.drop_column('mensagens', 'data_edicao')
    op.drop_column('mensagens', 'editada')
    op.drop_column('mensagens', 'data_entrega')
    op.drop_column('mensagens', 'status')
    op.drop_column('mensagens', 'tipo')
    op.drop_index(op.f('ix_leituras_grupo_id'), table_name='leituras_grupo')
    op.drop_table('leituras_grupo')
    op.drop_index(op.f('ix_mensagens_grupo_id'), table_name='mensagens_grupo')
    op.drop_table('mensagens_grupo')
    op.drop_index(op.f('ix_membros_grupo_id'), table_name='membros_grupo')
    op.drop_table('membros_grupo')
    op.drop_index(op.f('ix_status_usuarios_id'), table_name='status_usuarios')
    op.drop_table('status_usuarios')
    op.drop_index(op.f('ix_grupos_chat_id'), table_name='grupos_chat')
    op.drop_table('grupos_chat')
    # ### end Alembic commands ###
