"""add_cronograma_eventos_table

Revision ID: f80b2b33a570
Revises: d746a8d81c84
Create Date: 2025-11-27 20:36:48.125962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80b2b33a570'
down_revision: Union[str, None] = 'd746a8d81c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=True),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('porte', sa.String(length=50), nullable=True),
    sa.Column('er', sa.String(length=50), nullable=True),
    sa.Column('carteira', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('bairro', sa.String(length=200), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('cnae_principal', sa.String(length=50), nullable=True),
    sa.Column('descricao_cnae', sa.Text(), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=200), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('numero_funcionarios', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_empresa'), 'empresas', ['empresa'], unique=False)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_municipio'), 'empresas', ['municipio'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_id'), 'stages', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('admin', 'consultor', name='tipousuario'), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('modelo_carro', sa.String(length=200), nullable=True),
    sa.Column('placa_carro', sa.String(length=20), nullable=True),
    sa.Column('informacoes_basicas', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_placa_carro'), 'usuarios', ['placa_carro'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('dados_json', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('atribuicoes_empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=True),
    sa.Column('data_desativacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atribuicoes_empresas_id'), 'atribuicoes_empresas', ['id'], unique=False)
    op.create_table('company_pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('linha', sa.String(length=50), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('probabilidade', sa.Integer(), nullable=True),
    sa.Column('data_entrada_stage', sa.DateTime(), nullable=True),
    sa.Column('data_prevista_fechamento', sa.DateTime(), nullable=True),
    sa.Column('nome_contato', sa.String(length=200), nullable=True),
    sa.Column('email_contato', sa.String(length=200), nullable=True),
    sa.Column('telefone_contato', sa.String(length=50), nullable=True),
    sa.Column('cargo_contato', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_pipeline_id'), 'company_pipeline', ['id'], unique=False)
    op.create_table('cronograma_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposta', sa.String(length=100), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('sigla', sa.String(length=100), nullable=True),
    sa.Column('er', sa.String(length=200), nullable=True),
    sa.Column('porte', sa.String(length=50), nullable=True),
    sa.Column('solucao', sa.Text(), nullable=True),
    sa.Column('horas_totais', sa.Float(), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('consultor_nome', sa.String(length=200), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('regiao', sa.String(length=200), nullable=True),
    sa.Column('municipio', sa.String(length=200), nullable=True),
    sa.Column('uf', sa.String(length=50), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('celular', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('planejado', 'em_andamento', 'concluido', 'cancelado', 'pausado', name='statusprojeto'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_projetos_cnpj'), 'cronograma_projetos', ['cnpj'], unique=False)
    op.create_index(op.f('ix_cronograma_projetos_id'), 'cronograma_projetos', ['id'], unique=False)
    op.create_index(op.f('ix_cronograma_projetos_proposta'), 'cronograma_projetos', ['proposta'], unique=False)
    op.create_index(op.f('ix_cronograma_projetos_sigla'), 'cronograma_projetos', ['sigla'], unique=False)
    op.create_table('grupos_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['criador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_chat_id'), 'grupos_chat', ['id'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_leitura', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('editada', sa.Boolean(), nullable=False),
    sa.Column('data_edicao', sa.DateTime(), nullable=True),
    sa.Column('deletada', sa.Boolean(), nullable=False),
    sa.Column('resposta_para_id', sa.Integer(), nullable=True),
    sa.Column('anexo_url', sa.String(length=500), nullable=True),
    sa.Column('anexo_nome', sa.String(length=255), nullable=True),
    sa.Column('anexo_tamanho', sa.Integer(), nullable=True),
    sa.Column('reacoes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['resposta_para_id'], ['mensagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_id'), 'mensagens', ['id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PROSPECCAO_CRIADA', 'AGENDAMENTO_CRIADO', 'AGENDAMENTO_REALIZADO', 'EMPRESA_ATRIBUIDA', 'PROSPECCAO_ATUALIZADA', name='tiponotificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('usuario_origem_id', sa.Integer(), nullable=False),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_origem_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_table('prospeccoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('data_ligacao', sa.Date(), nullable=True),
    sa.Column('hora_ligacao', sa.Time(), nullable=True),
    sa.Column('resultado', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('porte', sa.String(length=50), nullable=True),
    sa.Column('lr', sa.String(length=50), nullable=True),
    sa.Column('id_externo', sa.String(length=100), nullable=True),
    sa.Column('cfr', sa.String(length=50), nullable=True),
    sa.Column('tipo_producao', sa.String(length=200), nullable=True),
    sa.Column('data_prospeccao', sa.Date(), nullable=True),
    sa.Column('follow_up', sa.Date(), nullable=True),
    sa.Column('nome_contato', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('celular', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('telefone_contato', sa.String(length=50), nullable=True),
    sa.Column('email_contato', sa.String(length=200), nullable=True),
    sa.Column('cargo_contato', sa.String(length=200), nullable=True),
    sa.Column('cnpj', sa.String(length=50), nullable=True),
    sa.Column('status_prospeccao', sa.String(length=100), nullable=True),
    sa.Column('responsavel', sa.String(length=200), nullable=True),
    sa.Column('opcoes', sa.Text(), nullable=True),
    sa.Column('retorno', sa.Text(), nullable=True),
    sa.Column('observacoes_prospeccao', sa.Text(), nullable=True),
    sa.Column('interesse_treinamento', sa.Boolean(), nullable=True),
    sa.Column('interesse_consultoria', sa.Boolean(), nullable=True),
    sa.Column('interesse_certificacao', sa.Boolean(), nullable=True),
    sa.Column('interesse_eventos', sa.Boolean(), nullable=True),
    sa.Column('interesse_produtos', sa.Boolean(), nullable=True),
    sa.Column('interesse_seguranca', sa.Boolean(), nullable=True),
    sa.Column('interesse_meio_ambiente', sa.Boolean(), nullable=True),
    sa.Column('outros_interesses', sa.Text(), nullable=True),
    sa.Column('potencial_negocio', sa.String(length=50), nullable=True),
    sa.Column('status_follow_up', sa.String(length=100), nullable=True),
    sa.Column('proxima_prospeccao_data', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospeccoes_id'), 'prospeccoes', ['id'], unique=False)
    op.create_table('status_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('ultima_atividade', sa.DateTime(), nullable=False),
    sa.Column('digitando_para', sa.Integer(), nullable=True),
    sa.Column('digitando_desde', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['digitando_para'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_status_usuarios_id'), 'status_usuarios', ['id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospeccao_id', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'realizado', 'vencido', name='statusagendamento'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospeccao_id'], ['prospeccoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_data_agendada'), 'agendamentos', ['data_agendada'], unique=False)
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_pipeline_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_arquivo', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_pipeline_id'], ['company_pipeline.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_table('company_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_pipeline_id', sa.Integer(), nullable=False),
    sa.Column('stage_anterior_id', sa.Integer(), nullable=True),
    sa.Column('stage_novo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_pipeline_id'], ['company_pipeline.id'], ),
    sa.ForeignKeyConstraint(['stage_anterior_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['stage_novo_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_stage_history_id'), 'company_stage_history', ['id'], unique=False)
    op.create_table('cronograma_atividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('carga_horas', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'concluida', 'cancelada', name='statusatividade'), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['cronograma_projetos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_atividades_id'), 'cronograma_atividades', ['id'], unique=False)
    op.create_table('cronograma_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Enum('consultoria', 'kickoff', 'reuniao_final', 'mentoria', 'diagnostico', 'programado', 'outros', name='categoriaevento'), nullable=False),
    sa.Column('periodo', sa.Enum('manha', 'tarde', 'dia_todo', name='periodoevento'), nullable=True),
    sa.Column('sigla_empresa', sa.String(length=100), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['cronograma_projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronograma_eventos_categoria'), 'cronograma_eventos', ['categoria'], unique=False)
    op.create_index(op.f('ix_cronograma_eventos_consultor_id'), 'cronograma_eventos', ['consultor_id'], unique=False)
    op.create_index(op.f('ix_cronograma_eventos_data'), 'cronograma_eventos', ['data'], unique=False)
    op.create_index(op.f('ix_cronograma_eventos_id'), 'cronograma_eventos', ['id'], unique=False)
    op.create_index(op.f('ix_cronograma_eventos_sigla_empresa'), 'cronograma_eventos', ['sigla_empresa'], unique=False)
    op.create_table('membros_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('silenciado', sa.Boolean(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=False),
    sa.Column('adicionado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adicionado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membros_grupo_id'), 'membros_grupo', ['id'], unique=False)
    op.create_table('mensagens_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('editada', sa.Boolean(), nullable=False),
    sa.Column('data_edicao', sa.DateTime(), nullable=True),
    sa.Column('deletada', sa.Boolean(), nullable=False),
    sa.Column('resposta_para_id', sa.Integer(), nullable=True),
    sa.Column('anexo_url', sa.String(length=500), nullable=True),
    sa.Column('anexo_nome', sa.String(length=255), nullable=True),
    sa.Column('anexo_tamanho', sa.Integer(), nullable=True),
    sa.Column('reacoes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['resposta_para_id'], ['mensagens_grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_grupo_id'), 'mensagens_grupo', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_pipeline_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('importante', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_pipeline_id'], ['company_pipeline.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('leituras_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ultima_mensagem_lida_id', sa.Integer(), nullable=True),
    sa.Column('data_leitura', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['ultima_mensagem_lida_id'], ['mensagens_grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leituras_grupo_id'), 'leituras_grupo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leituras_grupo_id'), table_name='leituras_grupo')
    op.drop_table('leituras_grupo')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_mensagens_grupo_id'), table_name='mensagens_grupo')
    op.drop_table('mensagens_grupo')
    op.drop_index(op.f('ix_membros_grupo_id'), table_name='membros_grupo')
    op.drop_table('membros_grupo')
    op.drop_index(op.f('ix_cronograma_eventos_sigla_empresa'), table_name='cronograma_eventos')
    op.drop_index(op.f('ix_cronograma_eventos_id'), table_name='cronograma_eventos')
    op.drop_index(op.f('ix_cronograma_eventos_data'), table_name='cronograma_eventos')
    op.drop_index(op.f('ix_cronograma_eventos_consultor_id'), table_name='cronograma_eventos')
    op.drop_index(op.f('ix_cronograma_eventos_categoria'), table_name='cronograma_eventos')
    op.drop_table('cronograma_eventos')
    op.drop_index(op.f('ix_cronograma_atividades_id'), table_name='cronograma_atividades')
    op.drop_table('cronograma_atividades')
    op.drop_index(op.f('ix_company_stage_history_id'), table_name='company_stage_history')
    op.drop_table('company_stage_history')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_index(op.f('ix_agendamentos_data_agendada'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_status_usuarios_id'), table_name='status_usuarios')
    op.drop_table('status_usuarios')
    op.drop_index(op.f('ix_prospeccoes_id'), table_name='prospeccoes')
    op.drop_table('prospeccoes')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_mensagens_id'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_grupos_chat_id'), table_name='grupos_chat')
    op.drop_table('grupos_chat')
    op.drop_index(op.f('ix_cronograma_projetos_sigla'), table_name='cronograma_projetos')
    op.drop_index(op.f('ix_cronograma_projetos_proposta'), table_name='cronograma_projetos')
    op.drop_index(op.f('ix_cronograma_projetos_id'), table_name='cronograma_projetos')
    op.drop_index(op.f('ix_cronograma_projetos_cnpj'), table_name='cronograma_projetos')
    op.drop_table('cronograma_projetos')
    op.drop_index(op.f('ix_company_pipeline_id'), table_name='company_pipeline')
    op.drop_table('company_pipeline')
    op.drop_index(op.f('ix_atribuicoes_empresas_id'), table_name='atribuicoes_empresas')
    op.drop_table('atribuicoes_empresas')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_usuarios_placa_carro'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_stages_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_empresas_municipio'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_empresa'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
